name: "user list clean"
on:
  push:
  schedule:
  # 定时任务
    - cron: '0 20 * * *'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://pwb.yuanzj.top/api/actions.php?name=clean" -k
